# Задание 1
Создайте numpy array с элементами от числа N до 0 
(например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [24]:
import numpy as np

N = int(input("Введите целое число: "))
array = np.arange(N-1, -1,-1)
array

Введите целое число: 10


array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

# Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [25]:
import numpy as np

N = int(input("Введите целое число: "))
matrix = np.diag(np.arange(N, -1,-1))
diagonal = sum(np.diag(matrix))
print(matrix)
print('Сумма диагонали матрицы: ',diagonal)

Введите целое число: 5
[[5 0 0 0 0 0]
 [0 4 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 2 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 0]]
Сумма диагонали матрицы:  15


# Задание 3
Решите систему уравнений:

4x + 2y + z = 4

x + 3y = 12

5y + 4z = -3

In [15]:
a = np.array([[4,2,1],[1,3,0],[0,5,4]])
b = np.array([4,12,-3])

from numpy import linalg

print(linalg.solve(a,b))
print(np.allclose(np.dot(a,linalg.solve(a,b)),b))

[ 0.46666667  3.84444444 -5.55555556]
True
